name = "miniflare-typescript-esbuild-jest"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

[build]
command = "node build.js"

[[ d1_databases ]]
binding = "DB"
database_name = "blahaj-app"
database_id = "ef34adf7-e2e3-426c-b268-dd625bb80063"